
Training (Loss: 4.2759, output_max: 13):   0%|          | 1/1000 [00:05<1:24:43,  5.09s/it]
Traceback (most recent call last):
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\PureMLP.py", line 148, in <module>
    main(model)
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\PureMLP.py", line 119, in main
    assert False
AssertionError
[[0.02078945 0.00879461 0.01815933 ... 0.03010084 0.01263091 0.01369176]
 [0.01252901 0.0111402  0.01200409 ... 0.02745651 0.01533386 0.01964877]
 [0.01824558 0.03533379 0.00984578 ... 0.02611958 0.01069461 0.00878537]
 ...
 [0.02337229 0.02704982 0.01132188 ... 0.00942271 0.00713596 0.02181649]
 [0.01290097 0.012776   0.00967925 ... 0.0095475  0.00860527 0.011272  ]
 [0.01685682 0.00949274 0.01139515 ... 0.01830039 0.0155597  0.01926977]]